
AWC_CODECS = {
    0x00: 'PCM',
    0x01: 'PCM',
    0x04: 'IMA',
    0x05: 'XMA2',
    0x07: 'MPEG',
    0x08: 'Vorbis',
    0x0C: 'DSP',
    0x0F: 'ATRAC9',
    0x10: 'DSP-streamed',
}


REL98_SOUND_TYPES = {
    0x00: 'Sound', #unused?
    0x01: 'LoopingSound',
    0x02: 'EnvelopeSound',
    0x03: 'TwinLoopSound',
    0x04: 'SpeechSound',
    0x05: 'OnStopSound',
    0x06: 'WrapperSound',
    0x07: 'SequentialSound',
    0x08: 'StreamingSound', #awc channel list
    0x09: 'RetriggeredOverlappedSound',
    0x0a: 'CrossfadeSound',
    0x0b: 'CollapsingStereoSound',
    0x0c: 'SimpleSound', #awc channel
    0x0d: 'MultitrackSound', #awc track
    0x0e: 'RandomizedSound',
    0x0f: 'EnvironmentSound',
    0x10: 'DynamicEntitySound',
    0x11: 'SequentialOverlapSound',
    0x12: 'ModularSynthSound',
    0x13: 'GranularSound',
    0x14: 'DirectionalSound',
    0x15: 'KineticSound',
    0x16: 'SwitchSound',
    0x17: 'VariableCurveSound',
    0x18: 'VariablePrintValueSound',
    0x19: 'VariableBlockSound',
    0x1a: 'IfSound',
    0x1b: 'MathOperationSound',
    0x1c: 'ParameterTransformSound',
    0x1d: 'FluctuatorSound',
    0x1e: 'AutomationSound',
    0x1f: 'ExternalStreamSound',
    0x20: 'SpeechSelectorSound',
    0x21: 'InstanceLimitingSound',
    0x22: 'MixerPatchSound',
    0x23: 'ContextSound',
    0x24: 'CollapsingPannedSound',
    0x25: 'GraphicalEnvelopeSound',
    0x26: 'OnLimitSound',
    0x27: 'GameEventSound',
    0x28: 'NetworkSound',
    0x29: 'SoundSet',
    0x2a: 'NoteMap',
    0x2b: 'SoundSetList',
    0x2c: 'SoundHashList',
    0x2d: 'InstanceGroup',
    0x2e: 'SoundCondition',
    0x2f: 'SoundConditionVariableList',
    0x30: 'SoundOverrideMap',
    0x31: 'SharedSettings',
    0x32: 'SoundSetSet',
}    


REL325_SCRIPT_TYPES = {
    0x04: 'VehicleAudioSettings?',
    0x08: 'AudioMaterial?',
    0x0f: 'SpeechContext?',
    0x12: 'SpeechParams?',
    0x13: 'Contexts?',
    0x14: 'BoatAudioSettings?',
    0x19: 'MovementSettings?',
    0x22: 'PedVoiceGroups?',
    0x2a: 'AmbientZone',
    0x2c: 'AmbientZoneList',
    0x2f: 'AmbientZone?',
    0x31: 'Interiors?',
    0x33: 'InteriorSettings?',
    0x3d: 'CarAudioSettings?',

    0x44: 'StemMix',
    0x46: 'StemMixFloat?',
    0x49: 'InteractiveMusicMood',
    0x4a: 'StartTrackAction',
    0x4b: 'StopTrackAction',
    0x4c: 'SetMoodAction',
    0x4d: 'MusicEvent?',
    0x4e: 'StartActionList?',
    0x4f: 'StopActionList?',
   #0x50: '?',
   #0x51: '?',
    0x52: 'StartOneShotAction',
    0x53: 'StopOneShotAction',
    0x54: 'MusicBeat',
    0x55: 'MusicBar',
    0x5a: 'AnimalSounds',
    0x5d: 'MicSettingsReference?',
    0x5e: 'MicrophoneSettings',

    0x65: 'ExplosionsAudioSettings?',

    0xFF: 'EventIndex?',
}
